//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datingo.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentParent
    {
        public int commentId { get; set; }
        public string parentProfile { get; set; }
        public string comment { get; set; }
        public string commentOwner { get; set; }
        public System.DateTime commentDate { get; set; }
    
        public virtual userAcc userAcc { get; set; }
    }
}
