//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datingo.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userAcc()
        {
            this.commentParent = new HashSet<commentParent>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string userPw { get; set; }
        public string userMail { get; set; }
        public string userGender { get; set; }
        public string userAd { get; set; }
        public string userSoyad { get; set; }
        public Nullable<int> userBoy { get; set; }
        public Nullable<int> userKilo { get; set; }
        public string userHair { get; set; }
        public string userEye { get; set; }
        public string userCountry { get; set; }
        public string userFavTeam { get; set; }
        public string userBurc { get; set; }
        public string userFavMusic { get; set; }
        public string userFavFilm { get; set; }
        public string userMeslek { get; set; }
        public string userEgitim { get; set; }
        public byte[] userPhoto { get; set; }
        public Nullable<System.DateTime> userBirthday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentParent> commentParent { get; set; }
    }
}
